version: '3.1'
services:
  minecraft-exporter:
    image: 'nkimball/minecraft_exporter:v4'
    environment:
      RCON_HOST: 
      RCON_PORT:
      RCON_PASSWORD:
      WORLD_DIR: "/world"
      LOG_LEVEL: INFO
    ports:
    - 9700:8000
    volumes:
    - ./test_world:/world:ro
