version: '3.1'
services:
  minecraft-exporter:
    image: 'joshi425/minecraft_exporter'
    environment:
      RCON_HOST: 
      RCON_PORT:
      RCON_PASSWORD:
      WORLD_DIR: "/world"
      LOG_LEVEL: INFO
    ports:
    - 9700:8000
    volumes:
    - /path/to/minecraft/world:/world:ro
